# Generated by Django 5.0.4 on 2024-04-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grabproject', '0002_project_folder_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='folder_path',
        ),
        migrations.AddField(
            model_name='project',
            name='picture',
            field=models.FileField(default='newfile', upload_to='media/'),
            preserve_default=False,
        ),
    ]
