# Generated by Django 5.0.4 on 2024-04-19 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grabproject', '0003_remove_project_folder_path_project_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
