# Generated by Django 5.0.4 on 2024-04-20 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grabproject', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
