# Generated by Django 5.0.4 on 2024-04-28 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grabproject', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadProject',
        ),
    ]
